name: tikweb_test_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  location: ^3.2.4
  http: ^0.12.2
  get: ^3.24.0
  intl: ^0.16.1
  image_picker: ^0.6.7+14
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.0.0
  double_back_to_close: ^1.0.2+mit
  email_validator: ^1.0.6
  circular_profile_avatar: ^1.0.8
  flutter_spinkit: ^4.1.2+1
  image_cropper: ^1.3.1
  google_maps_flutter: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.3
  flutter_launcher_name: ^0.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tikweb.png"

flutter_launcher_name:
  name: "Tikweb Test"

flutter:

  uses-material-design: true

  assets:
    - assets/images/